### ISSUE TITLE
"'Response' object has no attribute '_headers'"

### ISSUE THREAD

**Issue by LiamK** [chibisov/drf-extensions#314] opened 2021-06-16 00:55 UTC
I think I found an issue.  
After updates (of everything basically) things appear stable, however the API was reporting
"'Response' object has no attribute '_headers'"

I commented out line 91 in rest_framework_extensions/cache/decorators.py
#response._headers.copy()
and it went away.  I'm guessing this is caused by a change in Django 3.2.  The introduced a HttpResponse.headers field, but I tried replacing it like this and got a (different) error (not enough values to unpack (expected 3, got 2))
response.headers.copy()

Django==3.2
djangorestframework==3.12.4
drf-extensions==0.7.0
Python 3.9.1

**Comment by daggaz** [comment] 2021-06-21 14:04
duplicate of #306

**Comment by domdinicola** [comment] 2021-07-16 17:51
duplicate of https://github.com/chibisov/drf-extensions/issues/313

**Comment by auvipy** [comment] 2021-07-17 17:35
i will try to cut on monday

**Comment by auvipy** [comment] 2021-07-30 08:07
done. please consider donating for my time

**Closed by auvipy** 2021-07-30 08:07 UTC
