### ISSUE TITLE
Routers fails to build urls for viewsets with @list_route methods

### ISSUE THREAD

**Issue by AdrianRibao** [chibisov/drf-extensions#122] opened 2016-01-28 09:00 UTC
If a viewset has a custom method decorated with `@list_route`, the router it adds the url with a required `pk` parameter.

I'm talking about root routes, not nested ones, I didn't try with a nested route,

**Comment by cancan101** [comment] 2016-01-29 22:14
Dupe of #91

**Closed** 2016-01-30 15:05 UTC
